config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'pages#home'
  resources :articles do
  	resources :comments 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	is_impressionable
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true
	validates :content, presence: true
	validates :user_id, presence: true

	def self.search(search)
		where("title || content ILIKE ?", "%#{search}%")
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :article, dependent: :destroy
  has_many :comment, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  impressionist :actions => [:show]
    
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.search(params[:search])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    impressionist(@article)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.article.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end

    #Require same user before update or delete
    def require_same_user
      if current_user != @article.user
        flash[:notice] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_article
	before_action :find_comment, only: [:edit, :update, :destroy]
	before_action :authenticate_user!
	before_action :require_same_user, except: [:create]

	def create
		@comment = @article.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@comment.content = comment_params
		if @comment.update(comment_params)
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to article_path(@article)
	end


	private
	def comment_params
		params.require(:comment).permit(:content)
	end

	def find_article
		@article = Article.find(params[:article_id])
	end

	def find_comment
		@comment = @article.comments.find(params[:id])
	end

	def require_same_user
		if current_user != @comment.user
			flash[:notice] = "You can only edit or delete your own comment"
			redirect_to article_path(@article)
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if user_signed_in?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(content)
	  @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
	  @markdown.render(content)
	end   
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        
        <div class="article-body">
          <%= truncate(markdown(article.content), length: 100, escape: false) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.email %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %>
            </small>
          </div>
        
        </div>
        <% if user_signed_in? && (current_user == article.user )  %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete this article", article_path(article), method: :delete,
                                data: {confirm: "Are you sure to delete this article?"}, 
                                class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
 
 
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: article %>

<div class='row'>
  <div class='col-md-12'>
    <%= form_for article, :html => {class: "form-horizontal", role: "form"} do |f| %>
    
      <div class="form-group">
        <div class="col-sm-2 control-label">
          <%= f.label :title %> 
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-2 control-label">  
          <%= f.label :content %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
      
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
       [ <%= link_to "Cancel request and return", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 align='center'>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
  <ul class="listing">
      <div class="row center">
        <div class="col-md-4 col-md-offset-4">
          <li>Created by: <%= @article.user.email %></li>
          <li>Views count: <%= @article.impressionist_count %>
        </div>
      </div>
    </ul>
    <% end %>
  <h4 class="center description">
    <strong>Content:</strong>
  </h4>
  <hr>
  <%= markdown(@article.content).html_safe %>
  <div class="article-actions">
    <% if user_signed_in? && (current_user == @article.user) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete,
                          data: {confirm: "Are you sure to delete this article?"}, 
                          class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success"%>
  </div>
</div>

<h3 align="Center" class="col-xs-8 col-xs-offset-2">Comments:</h3>
<%= render @article.comments %>
<% if user_signed_in? %>
  <%= render "comments/form", comment: Comment.new %>
<% end %>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-sm">      
      <div class="comment-body">
        <%= markdown(comment.content).html_safe %>
        <div class="article-meta-details">
          <small>Created by: <%= comment.user.email %>,
            <%= time_ago_in_words(comment.created_at) %> ago,
            last updated: <%= time_ago_in_words(comment.updated_at) %>
          </small>
        </div>
      
      </div>
      <% if user_signed_in? && (current_user == comment.user )  %>
        <div class="article-actions">
          <%= link_to "Edit this article", edit_article_comment_path(comment.article, comment), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_comment_path(comment.article, comment), method: :delete,
                              data: {confirm: "Are you sure to delete this article?"}, 
                              class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for [@article, comment], :html => {class: "form-horizontal", role: "form"} do |f| %>
    
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.text_area :content, rows: 4, class: "form-control", placeholder: "Comment..." %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit("Comment", class: 'btn btn-primary btn-lg') %>
        </div>
      </div>
      
    <% end %>

    <div class="col-xs-4 col-xs-offset-4">
       [ <%= link_to "Cancel request and return", article_path(@article) %> ]
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<h1 align="center">Edit comment</h1>
<%= render 'comments/form', comment: @comment %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-info %>'>
        <a href="#" class="close" data-dismiss="alert">&#215</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>

        <!-- Log in/out logic -->
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
            </ul>
          </li>
        <% end %>
        <form class="navbar-form navbar-left">
            
          <div class="form-group">
            <%= form_tag(articles_path, :method => "get", id: "search-form" ) do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Articles", class: "form-control" %>
              <%= submit_tag "Search", class: "btn btn-default" %>
            <% end %>
          </div>
        </form>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <!-- Log in/out logic -->
        <% if user_signed_in? %>        
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path%></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigation' %>
  	<%= render 'layouts/messages' %>
  	<div class="container">
  		<%= yield %>
  	</div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>MY BLOG</h1>
  <%= link_to "Sign up now", new_user_registration_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "erros") %>
            prohibited this <%= obj.class.name.downcase %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>